### ISSUE TITLE
How can I add new dataset?

### ISSUE THREAD

**Issue by pyo9912** [kmj0792/PolarDSN#3]

**Comment by kmj0792** [comment]
Thank you for your question!
To add a new dataset, please follow these steps:
1. Assign unique IDs to all users in the dataset, starting from 1 up to the total number of users.

2. The timestamp represents the elapsed time in seconds since the Unix epoch (January 1, 1970, 00:00:00 UTC). You can convert datetime information in the yy/mm/dd/tt format to timestamp values AS as described link: https://stackoverflow.com/questions/3694487/in-python-how-do-you-convert-seconds-since-epoch-to-a-datetime-object

3. If the dataset includes weight information, ensure that positive edges have positive weights, and negative edges have negative weights. If weight information is missing, assign a weight of 1 to positive edges and -1 to negative edges.

If you have any further questions, feel free to reach out!
